Subroutine Type2701

! Object: Modulating Air-to-Water Heat Pump
! Simulation Studio Model: Type2701
! 

! Author: 
! Editor: 
! Date:	 February 19, 2022
! Editing history: 
!                 - February 19, 2022: Type creation
!                 - March 11, 2022: Changing the conditions for which the heat pump is off
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Logical Unit for Heating Data	- [-Inf;+Inf]
!			Number of Partial Loads_Heating	- [1;+Inf]
!			Number of Water Temperatures_Heating	- [1;+Inf]
!			Number of Dry bulb Temperatures_Heating	- [1;+Inf]
!			Specific Heat of Liquid Stream	kJ/kg.K [0;+Inf]
!			Rated Heating Capacity	kJ/hr [0;+Inf]
!			Rated Coefficient of Performance (COP)	- [0;+Inf]
!			Minimum Capacity Ratio (CRmin)	- [0;+Inf]
!			Activation CR	- [0;+Inf]
!			Degradation Coefficient (Cd)	- [0;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Inlet Fluid Temperature	C [-Inf;+Inf]
!			Inlet Fluid Flowrate	kg/hr [0;+Inf]
!			Supply Temperature	C [-Inf;+Inf]
!			Dry bulb Temperature	C [-Inf;+Inf]
!			Heating Control Signal	- [0;1]

! *** 
! *** Model Outputs 
! *** 
!			Outlet Fluid Temperature	C [0;+Inf]
!			Outlet Fluid Flowrate	kg/hr [0;+Inf]
!			Heating Power	kJ/hr [0;+Inf]
!			Electric Power	kJ/hr [0;+Inf]
!			COP	- [0;+Inf]
!			CR	- [0;1]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Studio)
!***********************************************************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


Use TrnsysConstants
Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type2701

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
Implicit None

Double Precision Timestep,Time
Integer CurrentUnit,CurrentType


!    PARAMETERS
Integer Logical_Unit
DOUBLE PRECISION Number_of_Partial_Loads
DOUBLE PRECISION Number_of_Water_Temperatures
DOUBLE PRECISION Number_of_Dry_bulb_Temperatures
DOUBLE PRECISION Specific_Heat
DOUBLE PRECISION Rated_Heating_Cap
DOUBLE PRECISION Rated_COP
DOUBLE PRECISION Min_Cap_Ratio
DOUBLE PRECISION Activation_CR
DOUBLE PRECISION Deg_Coef

!    INPUTS
DOUBLE PRECISION Inlet_Fluid_Temp
DOUBLE PRECISION Inlet_Fluid_Flowr
DOUBLE PRECISION Supply_Temperature
DOUBLE PRECISION Dry_bulb_Temperature
DOUBLE PRECISION Control_Signal

!    OTHER
Integer nx,nval(3),ny,nval_a(3),nx_a,ny_a
DOUBLE PRECISION CRR,fcorr,Outlet_Fluid_Temp,Outlet_Fluid_Temp_at_CR1,Outlet_Fluid_Flowr,CR,cap_req,cap_at_CR1,COP_at_CR1, &
          capacity_norm,COP_norm,capacity_h,COP,el_power_h,X(3),Y(2),A(3),B(2)
Logical onHeat
Character (len=maxMessageLength) message1

message1 = 'The heat pump model was unable to correctly read from the supplied heat pump data files.  Please check the location and format of the required data files and re-run the simulation.'

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! Get the Global Trnsys Simulation Variables
Time = getSimulationTime()
Timestep = getSimulationTimeStep()
CurrentUnit = getCurrentUnit()
CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! Set the Version Number for This Type
If(getIsVersionSigningTime()) Then
    Call SetTypeVersion(17)
    Return
EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! Do Any Last Call Manipulations Here
If(getIsLastCallofSimulation()) Then
    Return
EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
If(getIsEndOfTimestep()) Then
    Return
EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! Do All of the "Very First Call of the Simulation Manipulations" Here
If(getIsFirstCallofSimulation()) Then
    !Tell the TRNSYS Engine How This Type Works
    Call SetNumberofParameters(10)           !The number of parameters that the the model wants
    Call SetNumberofInputs(5)                !The number of inputs that the the model wants
    Call SetNumberofDerivatives(0)           !The number of derivatives that the the model wants
    Call SetNumberofOutputs(6)               !The number of outputs that the the model produces
    Call SetIterationMode(1)                 !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
    Call SetNumberStoredVariables(0,0)       !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
     
    !Set the Correct Input and Output Variable Types
    Call SetInputUnits(1,'TE1')     !°C   
    Call SetInputUnits(2,'MF1')     !kg/hr
    Call SetInputUnits(3,'TE1')     !°C 
    Call SetInputUnits(4,'TE1')     !°C
    Call SetInputUnits(5,'CF1')     !control function
      
    Call SetOutputUnits(1,'TE1')    !°C 
    Call SetOutputUnits(2,'MF1')    !kg/hr			
    Call SetOutputUnits(3,'PW1')    !kJ/hr
    Call SetOutputUnits(4,'PW1')    !kJ/hr
    Call SetOutputUnits(5,'DM1')    !dimensionless
    Call SetOutputUnits(6,'DM1')    !dimensionless
    Return
EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
If (getIsStartTime()) Then
    Logical_Unit = JFIX(getParameterValue(1)+0.1)
    Number_of_Partial_Loads = JFIX(getParameterValue(2)+0.1)
    Number_of_Water_Temperatures = JFIX(getParameterValue(3)+0.1)
    Number_of_Dry_bulb_Temperatures = JFIX(getParameterValue(4)+0.1)
    Specific_Heat = getParameterValue(5)
    Rated_Heating_Cap = getParameterValue(6)
    Rated_COP = getParameterValue(7)
    Min_Cap_Ratio = getParameterValue(8)
    Activation_CR = getParameterValue(9)
    Deg_Coef = getParameterValue(10)
! Check the Parameters for Problems (#,ErrorType,Text)
    If (Logical_Unit < 10) Call FoundBadParameter(1,'Fatal','The logical unit number for the file with the heating performance data cannot be less than 10.')
    If (Number_of_Partial_Loads < 1) Call FoundBadParameter(2,'Fatal','The number of partial load steps in heating cannot be less than 1.')
    If (Number_of_Water_Temperatures < 1) Call FoundBadParameter(3,'Fatal','The number of water temperature steps in heating cannot be less than 1.')
    If (Number_of_Dry_bulb_Temperatures < 1) Call FoundBadParameter(4,'Fatal','The number of dry bulb steps in heating cannot be less than 1.')
    If (Specific_Heat < 0) Call FoundBadParameter(5,'Fatal','The specIfic heat of the liquid stream cannot be negative.')
    If (Rated_Heating_Cap <= 0) Call FoundBadParameter(6,'Fatal','The rated heating capacity must be greater than 0.')
    If (Rated_COP <= 0) Call FoundBadParameter(7,'Fatal','The rated COP must be greater than 0.')
    If (Min_Cap_Ratio < 0) Call FoundBadParameter(8,'Fatal','The minimum capacity ratio must be 0 or greater than 0.')
    If (Activation_CR < 0) Call FoundBadParameter(9,'Fatal','The activation capacity ratio must be 0 or greater than 0.')
    If (Deg_Coef < 0) Call FoundBadParameter(10,'Fatal','The correction factor must be 0 or greater than 0.')
    If (ErrorFound()) Return
          
! Set the Initial Values of the Outputs (#,Value)
    Call SetOutputValue(1,getInputValue(1)) ! Outlet Fluid Temperature
    Call SetOutputValue(2,getInputValue(2)) ! Outlet Fluid Flowrate
    Call SetOutputValue(3,0.d0) ! Heating Power
    Call SetOutputValue(4,0.d0) ! Electric Power
    Call SetOutputValue(5,0.d0) ! COP
    Call SetOutputValue(6,0.d0) ! CR
    Return
EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! ReRead the Parameters if Another Unit of This Type Has Been Called Last
If(getIsReReadParameters()) Then
    !Read in the Values of the Parameters from the Input File
    Logical_Unit = jfix(getParameterValue(1)+0.1)
    Number_of_Partial_Loads = jfix(getParameterValue(2)+0.1)
    Number_of_Water_Temperatures = jfix(getParameterValue(3)+0.1)
    Number_of_Dry_bulb_Temperatures = jfix(getParameterValue(4)+0.1)
    Specific_Heat = getParameterValue(5)
    Rated_Heating_Cap = getParameterValue(6)
    Rated_COP = getParameterValue(7)
    Min_Cap_Ratio = getParameterValue(8)
    Activation_CR = getParameterValue(9)
    Deg_Coef = getParameterValue(10)
EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
! Read the Inputs
Inlet_Fluid_Temp = GetInputValue(1)
Inlet_Fluid_Flowr = GetInputValue(2)
Supply_Temperature = GetInputValue(3)
Dry_bulb_Temperature = GetInputValue(4)
Control_Signal = GetInputValue(5)
		

! Check the Inputs for Problems (#,ErrorType,Text)
If (Inlet_Fluid_Flowr < 0.) Call FoundBadInput(2,'Fatal','The inlet fluid flow rate is negative.')
If ((Control_Signal < 0.d0).or.(Control_Signal > 1.d0)) Call FoundBadInput(5,'Fatal','The control signal for heating stage must be between 0 and 1.')
If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

! Determine If the heat pump is operating in heating mode
If (Control_Signal >= 0.5) Then
    Control_Signal = 1.d0
    onHeat = .true.
Else
    Control_Signal = 0.d0
    onHeat = .false.
EndIf
      
! Heat Pump is off
If (Control_Signal < 0.5) Then
    COP = 0.d0
    capacity_h = 0.d0
    el_power_h = 0.d0
    Outlet_Fluid_Temp = Inlet_Fluid_Temp
    Outlet_Fluid_Flowr = Inlet_Fluid_Flowr
    CR = 0.d0
    cap_req = 0.d0
ElseIf (Inlet_Fluid_Flowr == 0.d0) Then
    COP = 0.d0
    capacity_h = 0.d0
    el_power_h = 0.d0
    Outlet_Fluid_Temp = Inlet_Fluid_Temp
    Outlet_Fluid_Flowr = 0.d0
    CR = 0.d0
    cap_req = 0.d0
ElseIf (Inlet_Fluid_Temp >= Supply_Temperature) Then
    COP = 0.d0
    capacity_h = 0.d0
    el_power_h = 0.d0
    Outlet_Fluid_Temp = Inlet_Fluid_Temp
    Outlet_Fluid_Flowr = Inlet_Fluid_Flowr
    CR = 0.d0
    cap_req = 0.d0
    
Else
! Find the performance for heating the water
    If (onHeat) Then
        !Get the rated catalog performance
        !calculate performance at maximum load
        
        nx = 3
        ny = 2

        nval(3) = Number_of_Water_Temperatures
        nval(2) = Number_of_Dry_bulb_Temperatures
        nval(1) = Number_of_Partial_Loads
        
        X(3) = Supply_Temperature                           !INLET WATER TEMPERATURE
        X(2) = Dry_bulb_Temperature                      !AMBIENT TEMPERATURE
        X(1) = 1.d0                               !MAX LOAD
        Call InterpolateData(Logical_Unit,nx,nval,ny,X,Y)
        If (ErrorFound()) Then
            Call Messages(-1,Message1,'FATAL',CurrentUnit,CurrentType)
            Return
        EndIf
    
        cap_at_CR1 = Rated_Heating_Cap*Y(1)
        COP_at_CR1 = Rated_COP*Y(2)
        
    
    !calculate performance at partial load
        nx_a = 3
        ny_a = 2
        

        nval_a(3) = Number_of_Water_Temperatures
        nval_a(2) = Number_of_Dry_bulb_Temperatures
        nval_a(1) = Number_of_Partial_Loads
        
        A(3) = Supply_Temperature                           !INLET WATER TEMPERATURE
          
        cap_req = Specific_Heat*Inlet_Fluid_Flowr*(Supply_Temperature-Inlet_Fluid_Temp)
        CRR = (cap_req) / (cap_at_CR1)
        
        A(2) = Dry_bulb_Temperature                      !AMBIENT TEMPERATURE        
        A(1) = CRR                                !PARTIAL LOAD                            
 
        Call InterpolateData(Logical_Unit,nx_a,nval_a,ny_a,A,B)
        If (ErrorFound()) Then
            Call Messages(-1,Message1,'FATAL',CurrentUnit,CurrentType)
            Return
        EndIf

      
        capacity_norm = Rated_Heating_Cap*B(1)     !KJ/H
        COP_norm = Rated_COP*B(2)            !dimensionless
        
        
        
        If (CRR >= 1.d0) Then
            CR = 1.d0
        Else
            CR = CRR
        EndIf
        
        
        If (CR >= 1.d0) Then
            Outlet_Fluid_Temp = Inlet_Fluid_Temp+(cap_at_CR1/(Specific_Heat*Inlet_Fluid_Flowr))
            Outlet_Fluid_Flowr = Inlet_Fluid_Flowr
            capacity_h = cap_at_CR1
            COP = COP_at_CR1
            el_power_h = capacity_h/COP
        
        ElseIf (Min_Cap_Ratio < CR < 1.d0) Then
            Outlet_Fluid_Temp = Inlet_Fluid_Temp+(capacity_norm/(Specific_Heat*Inlet_Fluid_Flowr))
            Outlet_Fluid_Flowr = Inlet_Fluid_Flowr
            capacity_h = capacity_norm
            COP = COP_norm
            el_power_h = capacity_h/COP
        
        ElseIf (Activation_CR < CR <= Min_Cap_Ratio) Then
            Outlet_Fluid_Temp = Inlet_Fluid_Temp+(cap_at_CR1/(Specific_Heat*Inlet_Fluid_Flowr))
            Outlet_Fluid_Flowr = Inlet_Fluid_Flowr
            capacity_h = cap_at_CR1
            fcorr = CR/((Deg_Coef*CR)+(1-Deg_Coef))
            COP = COP_at_CR1*fcorr
            el_power_h = capacity_h/COP
        EndIf    
    EndIf
 
    If (CR <= Activation_CR) Then
        Outlet_Fluid_Temp = Inlet_Fluid_Temp
        Outlet_Fluid_Flowr = Inlet_Fluid_Flowr
        COP = 0.d0
        capacity_h = 0.d0
        el_power_h = 0.d0
    EndIf
    
EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
Call SetOutputValue(1, Outlet_Fluid_Temp) ! Outlet Fluid Temperature
Call SetOutputValue(2, Outlet_Fluid_Flowr) ! Outlet Fluid Flowrate
Call SetOutputValue(3, capacity_h) ! Heating Power
Call SetOutputValue(4, el_power_h) ! Electric Power
Call SetOutputValue(5, COP) ! COP
Call SetOutputValue(6, CR) ! CR

!-----------------------------------------------------------------------------------------------------------------------
 
!-----------------------------------------------------------------------------------------------------------------------
Return
End
!-------------------------------------------------